// Generates rust/src/tables.rs: the Unicode general category of every code point and the invariant
// lower-case mapping of every UTF-16 unit, exactly as .NET computes them.
//
// Why (spec 005, research R1): Rust's standard library has no general-category API, and its case
// mapping follows the Unicode version of whichever compiler builds the crate (16 on Rust 1.85, 17 on
// current stable), so it would disagree with .NET on 8 units and change from one compiler to the next.
// The matcher's per-unit tests must answer as .NET's do, so the crate embeds tables taken from .NET
// itself. CI regenerates the file and fails on any difference.
//
// Run from rust/:  dotnet run tools/gen_tables.cs -- src/tables.rs
//
// The output is deterministic: LF line endings, no timestamp, and only the .NET major version in the
// header, so a patch release of .NET (which never changes Unicode data) does not change the file.

using System.Globalization;
using System.Text;

if (args.Length != 1)
{
    Console.Error.WriteLine("usage: dotnet run tools/gen_tables.cs -- <output path>");
    return 2;
}

string CodeOf(UnicodeCategory category) => category switch
{
    UnicodeCategory.UppercaseLetter => "Lu",
    UnicodeCategory.LowercaseLetter => "Ll",
    UnicodeCategory.TitlecaseLetter => "Lt",
    UnicodeCategory.ModifierLetter => "Lm",
    UnicodeCategory.OtherLetter => "Lo",
    UnicodeCategory.NonSpacingMark => "Mn",
    UnicodeCategory.SpacingCombiningMark => "Mc",
    UnicodeCategory.EnclosingMark => "Me",
    UnicodeCategory.DecimalDigitNumber => "Nd",
    UnicodeCategory.LetterNumber => "Nl",
    UnicodeCategory.OtherNumber => "No",
    UnicodeCategory.SpaceSeparator => "Zs",
    UnicodeCategory.LineSeparator => "Zl",
    UnicodeCategory.ParagraphSeparator => "Zp",
    UnicodeCategory.Control => "Cc",
    UnicodeCategory.Format => "Cf",
    UnicodeCategory.Surrogate => "Cs",
    UnicodeCategory.PrivateUse => "Co",
    UnicodeCategory.ConnectorPunctuation => "Pc",
    UnicodeCategory.DashPunctuation => "Pd",
    UnicodeCategory.OpenPunctuation => "Ps",
    UnicodeCategory.ClosePunctuation => "Pe",
    UnicodeCategory.InitialQuotePunctuation => "Pi",
    UnicodeCategory.FinalQuotePunctuation => "Pf",
    UnicodeCategory.OtherPunctuation => "Po",
    UnicodeCategory.MathSymbol => "Sm",
    UnicodeCategory.CurrencySymbol => "Sc",
    UnicodeCategory.ModifierSymbol => "Sk",
    UnicodeCategory.OtherSymbol => "So",
    UnicodeCategory.OtherNotAssigned => "Cn",
    _ => throw new InvalidOperationException($"unknown category {category}"),
};

// Runs of equal category over U+0000–U+10FFFF. GetUnicodeCategory(int) reports surrogate code points
// as Surrogate, which is what the per-unit lookups need.
var runs = new List<(int Start, string Category)>();
string? previous = null;
for (int codePoint = 0; codePoint <= 0x10FFFF; codePoint++)
{
    string category = CodeOf(CharUnicodeInfo.GetUnicodeCategory(codePoint));
    if (category != previous)
    {
        runs.Add((codePoint, category));
        previous = category;
    }
}

var lower = new List<(int Unit, int Lower)>();
for (int unit = 0; unit <= 0xFFFF; unit++)
{
    char mapped = char.ToLowerInvariant((char)unit);
    if (mapped != unit)
    {
        lower.Add((unit, mapped));
    }
}

var output = new StringBuilder();
void Line(string text = "") => output.Append(text).Append('\n');

Line($"// Generated by tools/gen_tables.cs from .NET {Environment.Version.Major} (Unicode data of");
Line("// System.Globalization.CharUnicodeInfo); do not edit. See research R1 of spec 005.");
Line();
Line("use crate::unicode::Category;");
Line("use crate::unicode::Category::*;");
Line();
Line("/// The start of every run of code points with the same general category, in order. The category of");
Line("/// a code point is that of the last run starting at or before it.");
Line("#[rustfmt::skip]");
Line($"pub(crate) static CATEGORY_RANGES: [(u32, Category); {runs.Count}] = [");
for (int i = 0; i < runs.Count; i += 6)
{
    var row = runs.Skip(i).Take(6).Select(run => $"(0x{run.Start:X4}, {run.Category})");
    Line("    " + string.Join(", ", row) + ",");
}
Line("];");
Line();
Line("/// The category of each ASCII unit, for the fast path.");
Line("#[rustfmt::skip]");
Line("pub(crate) const ASCII_CATEGORIES: [Category; 128] = [");
for (int i = 0; i < 128; i += 16)
{
    var row = Enumerable.Range(i, 16).Select(unit => CodeOf(CharUnicodeInfo.GetUnicodeCategory(unit)));
    Line("    " + string.Join(", ", row) + ",");
}
Line("];");
Line();
Line("/// Every UTF-16 unit whose `char.ToLowerInvariant` differs from itself, with its lower case, sorted.");
Line("#[rustfmt::skip]");
Line($"pub(crate) static LOWER: [(u16, u16); {lower.Count}] = [");
for (int i = 0; i < lower.Count; i += 6)
{
    var row = lower.Skip(i).Take(6).Select(pair => $"(0x{pair.Unit:X4}, 0x{pair.Lower:X4})");
    Line("    " + string.Join(", ", row) + ",");
}
Line("];");

File.WriteAllText(args[0], output.ToString(), new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
Console.WriteLine($"{args[0]}: {runs.Count} category runs, {lower.Count} lower-case pairs (.NET {Environment.Version})");
return 0;
