"""Build hooks for the persian-text-guard package (spec 004, research R4, R6 and R9).

The repository keeps exactly one copy of the shared inputs every port reads: ``VERSION`` and the word
lists in ``wordlists/``. These hooks turn them into package files at build time:

- the metadata hook sets the version from ``VERSION``, converted to PEP 440 (``1.4.0-dev.2`` becomes
  ``1.4.0.dev2``), and copies the root ``LICENSE`` and ``THIRD-PARTY-NOTICES.md`` next to this file;
- the build hook writes ``src/persian_text_guard/_wordlists.py`` and ``_version.py``.

All four outputs are git-ignored. An sdist contains them, so building a wheel from an unpacked sdist,
where there is no repository root, reuses the generated files instead.
"""

from __future__ import annotations

import shutil
from pathlib import Path
from typing import Any

from hatchling.builders.hooks.plugin.interface import BuildHookInterface
from hatchling.metadata.plugin.interface import MetadataHookInterface
from packaging.version import InvalidVersion, Version

HERE = Path(__file__).resolve().parent
PACKAGE = HERE / "src" / "persian_text_guard"
WORDLISTS_MODULE = PACKAGE / "_wordlists.py"
VERSION_MODULE = PACKAGE / "_version.py"

# The .NET embedding order: Persian, Finglish, English.
WORDLIST_FILES = ("persian.txt", "finglish.txt", "english.txt")
LICENSE_FILES = ("LICENSE", "THIRD-PARTY-NOTICES.md")


def _repo_root() -> Path | None:
    root = HERE.parent
    if (root / "VERSION").is_file() and (root / "wordlists").is_dir():
        return root
    return None


def _pep440_version(root: Path) -> str:
    path = root / "VERSION"
    raw = path.read_text(encoding="utf-8").strip()
    try:
        return str(Version(raw))
    except InvalidVersion as error:
        raise ValueError(f"{path}: '{raw}' is not a version PEP 440 can represent") from error


def _version_from_module() -> str:
    if not VERSION_MODULE.is_file():
        raise FileNotFoundError(
            f"{VERSION_MODULE} is missing: build from the repository, or from an sdist that contains it"
        )
    namespace: dict[str, Any] = {}
    exec(VERSION_MODULE.read_text(encoding="utf-8"), namespace)
    return str(namespace["__version__"])


def _write_if_changed(path: Path, content: str) -> None:
    if path.is_file() and path.read_text(encoding="utf-8") == content:
        return
    path.write_text(content, encoding="utf-8", newline="\n")


def _copy_if_changed(source: Path, target: Path) -> None:
    if target.is_file() and target.read_bytes() == source.read_bytes():
        return
    shutil.copyfile(source, target)


class CustomMetadataHook(MetadataHookInterface):
    """Sets ``version`` from ``VERSION`` and copies the licence files into ``python/``."""

    def update(self, metadata: dict[str, Any]) -> None:
        """Fill in the dynamic version."""
        root = _repo_root()
        if root is None:
            metadata["version"] = _version_from_module()
            return

        metadata["version"] = _pep440_version(root)
        for name in LICENSE_FILES:
            _copy_if_changed(root / name, HERE / name)


class CustomBuildHook(BuildHookInterface):  # type: ignore[type-arg]
    """Generates ``_wordlists.py`` and ``_version.py`` from the repository's shared files."""

    def initialize(self, version: str, build_data: dict[str, Any]) -> None:
        """Write the generated modules before the files are collected."""
        # hatchling always adds the nearest .gitignore to an sdist; here that is the repository's own,
        # which describes the repository, not this package. The allowlist (check_package.py) has no
        # place for it.
        if self.target_name == "sdist":
            force_include: dict[str, str] = build_data.get("force_include", {})
            for source, target in list(force_include.items()):
                if target == ".gitignore":
                    del force_include[source]

        root = _repo_root()
        if root is None:
            for path in (WORDLISTS_MODULE, VERSION_MODULE):
                if not path.is_file():
                    raise FileNotFoundError(
                        f"{path} is missing: build from the repository, or from an sdist that contains it"
                    )
            return

        texts = []
        for name in WORDLIST_FILES:
            text = (root / "wordlists" / name).read_text(encoding="utf-8").replace("\r\n", "\n")
            texts.append(text)

        literals = "".join(f"    {text!r},\n" for text in texts)
        _write_if_changed(
            WORDLISTS_MODULE,
            '"""Generated by hatch_build.py from wordlists/*.txt; do not edit.\n\n'
            "The bundled word-list files, in order: Persian, Finglish, English.\n"
            '"""\n\n'
            f"BUNDLED_WORD_LISTS: tuple[str, ...] = (\n{literals})\n",
        )
        _write_if_changed(
            VERSION_MODULE,
            '"""Generated by hatch_build.py from VERSION; do not edit."""\n\n'
            f'__version__ = "{_pep440_version(root)}"\n',
        )
